name: Release APK
on:
  push:
    branches:
      - main

permissions:
  id-token: write #required for AWS creds to work
  contents: write #allow tag push for versions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-2

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Prepare Signing Key
        env:
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          mkdir app/keystore
          echo "$KEYSTORE_PROPERTIES" > app/keystore/keystore.properties
          echo "$RELEASE_KEYSTORE"|base64 --decode > app/keystore/release-key.jks

      - name: Test
        run: ./gradlew test

      - name: Tag release
        run: ./gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=${{ github.actor }} -Prelease.customPassword=${{ github.token }}

      - name: Build APK
        run: ./gradlew assemble

      - name: Push to S3
        env:
          RELEASE_APK_S3_URI: ${{ secrets.RELEASE_APK_S3_URI }}
        run: |
          aws s3 mv ${RELEASE_APK_S3_URI} ${RELEASE_APK_S3_URI}archive/ --recursive --exclude "archive/*"
          aws s3 cp app/build/outputs/apk/release $RELEASE_APK_S3_URI --recursive --exclude "*" --include "*.apk"